# DATA ANALYTICS

In [ ]:
# Required:
    
# 1. Python -- Basics
# 2. Maths -- Diffentiation, Integration, P&C
# 3. Stats -- Mean, Median, Mode

In [ ]:
# Libraries  (4)

# 1. Numpy          --> Data Analysis Library
# 2. Pandas         --> Data Analysis Library
# 3. Matplotlib     --> Data Visulization Library
# 4. Seaborn        --> Data Visulization Library

In [ ]:
# 1. Numpy : Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object,
#            and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
#            Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic
#            data.

# ---> Numerical Python
# ---> Array, Matrix, Transpose Matrix
# ---> Used in AI --> sub domain --> Open CV (Computer Vision)

In [ ]:
# 2. Pandas : Pandas is an open-source library that is made mainly for working with relational or labeled data both easily and
#             intuitively. It provides various data structures and operations for manipulating numerical data and time series.
#             This library is built on top of the NumPy library. Pandas is fast and it has high performance & productivity for
#             users.
            
# ---> Panel Data

In [ ]:
# 3. Matplotlib : Matplotlib is an amazing visualization library in Python for 2D plots of arrays. Matplotlib is a
#                 multi-platform data visualization library built on NumPy arrays and designed to work with the broader SciPy
#                 stack. It was introduced by John Hunter in the year 2002.

#                 One of the greatest benefits of visualization is that it allows us visual access to huge amounts of data in
#                 easily digestible visuals. Matplotlib consists of several plots like line, bar, scatter, histogram etc.
                
# ---> Mathematical Plotting Library --> Rectangular box(0-255)

In [ ]:
# 4. Seaborn : Seaborn is an amazing visualization library for statistical graphics plotting in Python. It provides beautiful
#              default styles and color palettes to make statistical plots more attractive. It is built on the top of matplotlib
#              library and also closely integrated to the data structures from pandas.
#              Seaborn aims to make visualization the central part of exploring and understanding data. It provides
#              dataset-oriented APIs, so that we can switch between different visual representations for same variables for
#              better understanding of dataset.
                
# ---> Updated version of Matplotlib
# ---> Data Visulization
# ---> Also tell about Data Flow

# Numpy

In [1]:
import numpy as np

In [2]:
# Create Array

arr1 = np.array([1,2,3,4,5])
print("1-D Array", arr1)

1-D Array [1 2 3 4 5]


In [3]:
type(arr1)     # to find type

numpy.ndarray

In [4]:
arr1.ndim     # to find dimension

1

In [9]:
# Create 2-D Array

arr2 = np.array([[1,2,3,4]])
print("2-D Array", arr2)

2-D Array [[1 2 3 4]]


In [6]:
type(arr2)     #type

numpy.ndarray

In [7]:
arr2. ndim    #dimension

2

In [16]:
# 2-D Array

arr2 = np.array([[23,34,45,56],[5,6,7,8]])
print(arr2)

[[23 34 45 56]
 [ 5  6  7  8]]


In [17]:
type(arr2)

numpy.ndarray

In [18]:
arr2.ndim

2

# Shape and Size

In [19]:
arr2.size

8

In [20]:
arr2.shape    # rows and column

(2, 4)

In [32]:
# Create 3-d Array

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [26]:
type(arr3)

numpy.ndarray

In [27]:
arr3.ndim

3

In [31]:
arr3.shape

(1, 3, 3)

In [29]:
arr3.size

9

In [34]:
# WAP to slice data 5 from array?

arr3[0][1][1]

5

In [36]:
arr3[0][0][0]

1

In [37]:
arr3[0][0]

array([1, 2, 3])

In [38]:
arr3[0][1]

array([4, 5, 6])

In [40]:
# WAP to find Max/min?

arr3.max()

9

In [42]:
arr3.min()

1