In [9]:
# WAP to find common element in a list?

l1 = [1,2,3,4,5]
l2 = [2,6,7,5,8]
#f=0
for i in l1:
    for j in l2:
        if i==j:
            print("Common element is present",i)      # we can put any of them ( i or j )
            break
else:
    print("-1")

Common element is present 2
Common element is present 5
-1


In [13]:
a = [1,2,3,4,5]
b = [2,6,7,5,9]
def common(a,b):
    for i in a:
        for j in b:
            if i==j:
                print("common element is present",j)
            else:
                print("-1")
common(a,b)

-1
-1
-1
-1
-1
common element is present 2
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
common element is present 5
-1


In [ ]:
# WAP to make a array of 2 by 3?

In [14]:
import numpy as np

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
arr.shape

(2, 3)

In [17]:
arr.ndim

2

In [19]:
arr.size

6

In [20]:
# In a array if we put a string then -----

a1 = np.array([1,2,3,"Python"])
print(a1)

['1' '2' '3' 'Python']


In [21]:
a1.ndim

1

In [22]:
a1.size

4

In [23]:
a1.shape

(4,)

# Ones and Zeros

In [ ]:
# Syntax

#  np.zeros(shape)

In [24]:
np.zeros(0)

array([], dtype=float64)

In [25]:
np.zeros(1)

array([0.])

In [26]:
np.zeros(5)        # the output coming as a float

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((5), dtype=int)        #output coming as a integer

array([0, 0, 0, 0, 0])

In [28]:
np.zeros(10,20)

TypeError: Cannot interpret '20' as a data type

In [29]:
np.zeros([10,20])        # want to use list

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [30]:
np.zeros([10,20], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
# WAP to make a 3-D matrix by zeros?

np.zeros([1,3,3], dtype=int)                   

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
# Note: Here [1,3,3] where 1 means number of matix
#                          3 means number of rows
#                          3 number of columns

In [33]:
np.zeros([2,3,3], dtype=int)      # 2 matrix present

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [47]:
np.zeros([5,3,3], dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
# Syntax

#  np.ones(shape)

In [48]:
np.ones(0)

array([], dtype=float64)

In [49]:
np.ones(1)

array([1.])

In [50]:
np.ones(5)                   # output comes as a float 

array([1., 1., 1., 1., 1.])

In [52]:
np.ones((5), dtype=int)

array([1, 1, 1, 1, 1])

In [55]:
np.ones([3,6], dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [56]:
np.ones([2,3,3], dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [57]:
# WAP to make a data of Ones of having the shape of 5 by 6 with the help of tuple

np.ones((5,6), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#  ARANGE Function

In [ ]:
# In this function 1,2,3,4,5,............. number comes.

# Syntax

# np.arange(start, stop, stepsize)

In [58]:
np.arange(0)

array([], dtype=int32)

In [60]:
np.arange(1)

array([0])

In [61]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [63]:
np.arange(0,4)

array([0, 1, 2, 3])

In [64]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [66]:
np.arange(50,2,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [67]:
np.arange([20,2,--2])        # cannot come as a list so not comes as 2-D or 3-D

TypeError: unsupported operand type(s) for -: 'list' and 'int'

# Empty Function

In [ ]:
# Syntax

# np.empty(shape)

In [68]:
np.empty(0)

array([], dtype=float64)

In [69]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.empty(20)

array([8.47929980e-312, 8.47929961e-312, 8.47929961e-312, 8.47929961e-312,
       8.47929986e-312, 8.47928769e-312, 8.47929957e-312, 8.47929957e-312,
       8.47929957e-312, 8.47929956e-312, 8.47929957e-312, 8.47929961e-312,
       8.47929986e-312, 8.47929986e-312, 8.47929986e-312, 8.47931599e-312,
       8.47931599e-312, 8.47931599e-312, 8.47931599e-312, 8.47931598e-312])

In [71]:
np.empty(50)

array([8.47874105e-312, 8.47912336e-312, 1.69121096e-306, 1.06810200e-306,
       1.42413555e-306, 1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
       1.11260483e-306, 8.90098127e-307, 3.56034566e-307, 1.37961641e-306,
       1.39071445e-307, 6.23037996e-307, 8.90096769e-307, 1.00136897e-307,
       1.11258361e-307, 9.79101761e-307, 1.00136897e-307, 1.39071615e-307,
       8.01094494e-307, 9.34569047e-307, 8.01059862e-307, 9.34599604e-307,
       9.45697982e-308, 9.45697982e-308, 8.01062579e-307, 1.05695168e-307,
       1.16820876e-307, 1.39075774e-307, 1.16820537e-307, 9.45697982e-308,
       1.05695252e-307, 8.90096769e-307, 1.22383900e-307, 9.34564973e-307,
       8.01063937e-307, 1.39071445e-307, 9.79101081e-307, 8.90063496e-307,
       1.00136557e-307, 1.33508930e-307, 8.45596650e-307, 9.79099044e-307,
       9.45740422e-308, 7.56558386e-307, 1.20161594e-306, 8.46676321e-312,
       8.47934195e-312, 9.24997323e-307])

In [75]:
np.empty([30,2])

array([[8.44251093e-053, 8.47903769e-312],
       [1.02455801e+136, 8.47903769e-312],
       [1.39804304e-076, 8.47903769e-312],
       [1.25691833e-071, 8.47903769e-312],
       [4.46889451e-033, 8.47903769e-312],
       [6.01391314e-154, 8.47903769e-312],
       [2.78732211e+179, 8.47903769e-312],
       [1.39804304e-076, 8.47903769e-312],
       [7.12604404e-067, 8.47871932e-312],
       [0.00000000e+000, 6.38855069e-067],
       [2.12199579e-313, 2.54639495e-313],
       [1.08539798e-071, 8.47871932e-312],
       [0.00000000e+000, 6.01391519e-154],
       [2.12199579e-313, 2.54639495e-313],
       [4.85110480e-086, 8.47903769e-312],
       [2.37635557e-038, 8.47903769e-312],
       [1.02469942e+136, 8.47903769e-312],
       [1.39804304e-076, 8.47903769e-312],
       [9.96008463e-043, 8.47903769e-312],
       [6.01391314e-154, 8.47903769e-312],
       [2.79049289e+179, 8.47903769e-312],
       [1.03008591e-071, 8.47903769e-312],
       [1.39804304e-076, 8.47903769e-312],
       [6.0

# Indentity Function

In [ ]:
# Syntax

# np.identity(shape)

In [77]:
np.identity((3), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [80]:
np.identity((5), dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Transpose Matrix

In [81]:
# WAP to create a 3x3 Matrix?

a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])       # in 3-D

In [82]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [84]:
a.shape

(1, 3, 3)

In [85]:
a.size

9

In [86]:
a.ndim

3

In [87]:
# To Transpose the matrix------>


a.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [88]:
# WAP to create a 3x3 matrx in 2-D

b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
b.ndim

2

In [91]:
b.shape

(3, 3)

In [92]:
b.size

9

In [93]:
# To transpose this matrix---->

b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Lin Space

In [ ]:
# Syntax

# np.linspace(start, stop, number)     --> number means   how many no. wnat b/w start and stop

In [94]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [96]:
np.linspace(10,20,8)

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

# Axis=0 and Axis=1

In [ ]:
# Syntax

# a.sum(axis=....0   or   1)

# Axis = 0 ----------->Column
# Axis = 1 ----------->Rows

# ----> Sum of Column or Rows

In [107]:
# Create 2-D matrix

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [108]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
a.sum()         # sum of matrix

45

In [110]:
a.sum(axis = 1)       # sum of column

array([ 6, 15, 24])

In [111]:
a.sum(axis=0)        # sum of rows 

array([12, 15, 18])