In [1]:
import numpy as np

In [2]:
# WAP to calculate the sum of 3 by 2 matrix with respect to Row wise & Column wise.

arr = np.array([[1,2],[3,4],[5,6]])

In [3]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.sum()

21

In [6]:
# For Column

arr.sum(axis = 0)

array([ 9, 12])

In [7]:
# For Row

arr.sum(axis = 1)

array([ 3,  7, 11])

#  Sort, Max, Min

In [8]:
arr1 = np.array([[[23,78,4],[90,4,21],[78,56,900]]])

In [9]:
arr1

array([[[ 23,  78,   4],
        [ 90,   4,  21],
        [ 78,  56, 900]]])

In [11]:
arr1.shape

(1, 3, 3)

In [16]:
# Sort

arr1.sort()                     # small to big in each row

In [17]:
arr1

array([[[  4,  23,  78],
        [  4,  21,  90],
        [ 56,  78, 900]]])

In [18]:
# Max

arr1.max()

900

In [19]:
# Min

arr1.min()

4

# ArgSort(), ArgMin(), ArgMax()

In [23]:
arr2 = np.array([[[65,45,99],[90,45,65],[14,90,63]]])

In [24]:
arr2

array([[[65, 45, 99],
        [90, 45, 65],
        [14, 90, 63]]])

In [25]:
# argsort()
                                   # Sort by index method from small to big
arr2.argsort()

array([[[1, 0, 2],
        [1, 2, 0],
        [0, 2, 1]]], dtype=int64)

In [26]:
# argmax()
                                  # Index 2 which is 99 is Bigger
arr2.argmax()

2

In [27]:
# argmin()
                                  # Index 6 which is 14 is smaller
arr2.argmin()

6